### ISSUE TITLE
Laravel readme

### ISSUE THREAD

**Issue by abangcik** [iskandaraadk/jjcm#1]
Your readme file still use laravel readme file

**Comment by iskandaraadk** [comment]
Owh can you help with that?

**Comment by abangcik** [comment]
Sure

**Comment by abangcik** [comment]
Done

#a5b18b27f42a487d7bcb928984265d55b94f2e35

**Comment by iskandaraadk** [comment]
Next time use pull request

**Comment by abangcik** [comment]
Ok
